// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Models;

#nullable disable

namespace QuanLyKho.Migrations
{
    [DbContext(typeof(ITGDBContext))]
    [Migration("20230530141405_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyKho.Models.ChiTietNhapXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("dvt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_vt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_lap_phieu")
                        .HasColumnType("datetime2");

                    b.Property<float?>("sl_nhap")
                        .HasColumnType("real");

                    b.Property<float?>("sl_xuat")
                        .HasColumnType("real");

                    b.Property<string>("so_phieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_vt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChitietNhapxuats");
                });
#pragma warning restore 612, 618
        }
    }
}
